CREATE SCHEMA CLUBE_DO_LIVRO;

CREATE TABLE LIVRO (
    ID_LIVRO INT NOT NULL,
    NOME_LIVRO VARCHAR(100) NOT NULL,
    AUTORIA VARCHAR(100) NOT NULL,
    EDITORA VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (ID_LIVRO)
);

CREATE TABLE ESTOQUE (
    ID_LIVRO INT NOT NULL,
    QTD_ESTOQUE INT NOT NULL,
    PRIMARY KEY (ID_LIVRO),
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID_LIVRO)
);

CREATE TABLE VENDEDOR (
    ID_VENDEDOR INT NOT NULL,
    NOME_VENDEDOR VARCHAR(256) NOT NULL,
    PRIMARY KEY (ID_VENDEDOR)
);

CREATE TABLE VENDA (
    ID_PEDIDO INT NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    ID_LIVRO INT NOT NULL,
    QTD_VENDIDA INT NOT NULL,
    DATA_VENDA DATE NOT NULL,
    PRIMARY KEY (ID_VENDEDOR, ID_PEDIDO),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR),
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO(ID_LIVRO)
);

-- ADICIONAR CHAVE ESTRANGENRIA (ID_LIVRO) NA TABELA ESTOQUE
ALTER TABLE ESTOQUE ADD CONSTRAINT PK_ESTOQUE_LIVRO
FOREIGN KEY (ID_LIVRO)
REFERENCES LIVRO (ID_LIVRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- ADICIONAR CHAVE ESTRANGENRIA (ID_LIVRO) NA TABELA VENDA
ALTER TABLE VENDA ADD CONSTRAINT PK_VENDA_LIVRO
FOREIGN KEY (ID_LIVRO)
REFERENCES LIVRO (ID_LIVRO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

-- ADICIONAR CHAVE ESTRANGENRIA (ID_VENDEDOR) NA TABELA VENDA
ALTER TABLE VENDA ADD CONSTRAINT PK_VENDA_VENDEDOR
FOREIGN KEY (ID_VENDEDOR)
REFERENCES VENDEDOR (ID_VENDEDOR)
ON DELETE NO ACTION
ON UPDATE NO ACTION;